Feature/1699
CPMIDIAS/poc-back pull request #1
Opened 2021-09-30 13:59 UTC by yssgor

Instalação e configuração do Prisma Migration.

2021-09-30 14:25 UTC, fabriciompc requested changes

2021-09-30 14:25 UTC, fabriciompc commented on .env
> +# Environment variables declared in this file are automatically made available to Prisma.
Pode retirar os comentários do .env por que não é muito bom ter isso nesse arquivo.

2021-09-30 14:25 UTC, fabriciompc commented on .gitignore
> -/public/swagger.json
Essas linhas:
/build/
/public/swagger.json
Não deveriam permanecer??

2021-09-30 14:25 UTC, fabriciompc commented on docker-compose.yml
> +    #name: poc-back
Qual o motivo de tirar o nome da rede do docker-compose?

2021-09-30 14:25 UTC, fabriciompc commented on package.json
> +    "@prisma/client": "^3.1.1",
Existe o pacote @types/prisma? se houver pode instalar como dependencia de desenvolvimento.

2021-09-30 16:27 UTC, yssgor commented on .gitignore
> -/public/swagger.json
Isso foi um erro que passou despercebido, eu não lembro de ter tirado isso do gitignore, desculpa! Colocarei de volta.

2021-09-30 16:30 UTC, yssgor commented on docker-compose.yml
> +    #name: poc-back
O meu docker não inicia com o nome da rede. Ele apresenta esse erro:
`ERROR: The Compose file './docker-compose.yml' is invalid because:
networks.api value Additional properties are not allowed ('name' was unexpected)`
Porém também foi um erro meu de passar despercebido pelo o git o nome da rede ser cometado.

2021-10-01 20:57 UTC, fabriciompc approved these changes

2021-10-01 20:58 UTC, merged